en_test_inputs = [
'As a French citizen, I was moved, as I was when Germany was buffeted by storms; and there were also those disasters in the Azores ...',
'As a result of this, hundreds of Scottish boats have had to be scrapped and fishing communities have suffered.',
'As always, Mr Verheugen came out against the progressive trio of Commissioner Piebalgs, Commissioner Dimas and Commissioner Kroes.',
'As an outside observer, allow me to reiterate what I said earlier to Mrs González.',
'As draftsman of the opinion of the Committee on Foreign Affairs, Humans Rights, Common Security and Defence Policy on the report on nuclear sector related activities for the applicant countries of Central and Eastern Europe and the New Independent States, unanimously adopted on 27 October last year, I stressed the crucial importance of safety, defining it as a requirement for accession for new Member States of the Union.',
'As far as food and agricultural production are concerned, we must have a deep respect for people s clear right to information about the food they eat.',
'As far as whether our rights have been expanded or reduced, ladies and gentlemen, please read the report and look at the legislation.',
'As for the fourth point, Commissioner, I believe that we need to discuss it seriously: it concerns the structural policy and the Lisbon Strategy.',
'As for the new demands that have arisen with the entry into force of the Treaty of Lisbon, we support excellence in lawmaking and the demand for adequate resources to achieve this objective.',
'As he said, we shall hold a sitting specifically devoted to this subject within the Convention on 6 and 7 February.',
'As huge sums of money are involved in major sports, common rules and regulations should be drawn up to take account of the system s basic pillars, sportsmen and the organisers of sporting events.',
'As in this compromise, I naturally wish to highlight the importance of not interfering with the directive on the posting of workers.',
'As much as 20% of farmers total direct payments would be clawed back and transferred to some rural development measures or returned back into the CAP budget itself.',
'As previous speakers on this issue have indicated, the individual Member States have not implemented the criteria properly.',
'As regards the two amendments within the framework of the second reading, they clearly improve the quality of the text and the Commission can therefore accept them in full.',
'As regards timing, my advice would be that it is premature to talk about timetables at this stage: we should not take the second step before the first.',
'As regards your third question on the weakening of the principle of additionality, additionality is one of the basic principles of cohesion policy.',
'As the international community finally woke up to Indonesia s oppression, the idea that freedom was on its way grew in their minds.',
'As the questions say, the Board of the IAEA recently approved revised transport regulations including specifications for air transport applicable to all radioactive materials.',
'As the report states, there are also problems in reconciling work and family life that are relevant to equality between women and men in professional life.',
'As you know, these treaties deal with all categories of income, aimed to eliminate dual taxation, bilaterally harmonizing effective taxation rates at source and in the place of residence and avoiding tax invasion.',
'At Porto Alegre, in the face of the discredited image of Europe that the United States wants to disseminate everywhere, another Europe was also discussed, a Europe about whose shortcomings we have no illusions but which many envy us, a Europe that is a model of successful integration.',
'At least that is what this report is saying, and I think that makes sense.',
'At present, this region is full of memories.',
'At the beginning of March, the Council adopted conclusions that set up the broad political mandate and the main priorities for the EU at these meetings.',
'At the centre of this whole, newly-ignited, dispute, the disagreements we have, and the European crisis, is a single sentence uttered by founding father of the European Union, Jean Monnet, who said, ‘We are not uniting states; we are uniting people’.',
'At the heart of this is the destabilising attempt to make the courts subservient to the executive, something we witness the Italian Government doing on a daily basis by means unworthy of a civil State.',
'At the heart of this struggle, in which Colombia is a leading player, are the social question and the country’s location.',
'At the moment, however, we are witness to a more gradual approach.',
'At the moment, its most famous citizen is Mohammad Junus, who received the Nobel Peace Prize this year for his contribution to the fight against poverty by means of a system of microcredits.',
'At the same time, however, you cannot rewrite history.',
'At the same time, we are willing to consider these issues in a broader context.',
'At the time, Jacques Delors, the US Government and all the European leaders condemned these people for daring to rise up against communist and federalist regimes.',
'At this juncture, these are all the feasible and practical undertakings we can give to try and resolve an appalling and long-lasting bloody situation.',
'At this point, I would like to remind you of the debate we had two years ago regarding Turkeys accession.',
'Because of the common position on Burma, it was impossible to invite the Burmese delegation to the EU-ASEAN ministerial meeting in Berlin, which led to that meeting being cancelled.',
'Because this is a communication that achieved the broad consensus of the various parties involved, I should like to reiterate my support for the Commissions conclusions and for the aims proposed for developing practical policies to achieve active ageing and the involvement of all interested parties in defining policies in the field of social protection, inclusion and employment.',
'Before I move on to the question of the approach agreed upon in the Council, I would like to remind everyone of the timely and effective work instigated by the Commission and given the support of the Member States Standing Veterinary Committee to implement vital crisis measures imposed by the precautionary principle.',
]

fr_test_ins  = [
'Ce qui importe vraiment, cest de pouvoir remonter aux initiateurs au moyen de reconditionnements intermédiaires et de leur demander de rendre des comptes pour toute fausse déclaration, négligence ou incompétence',
'Ce rapport appartient à la catégorie des textes marqués par la ridicule obsession de la réglementation jusque dans les détails',
'Ce serait une erreur de ne pas inclure dans un plan de gestion les déchets qui ne sont pas destinés à une élimination finale',
'Ce sommet est intervenu un an après l’adoption des quatre feuilles de route relatives aux espaces communs, de sorte qu’il nous offrait une excellente occasion d’examiner les progrès faits depuis lors',
'Ce sont ces points et la possibilité d’introduire des considérations sociales et environnementales qui ont, plus que toute autre chose, forcé la conciliation',
'Ce séminaire a réuni des experts de toute l’Union européenne - y compris des nouveaux États membres et de l’Organisation mondiale de la santé - et a abordé, entre autres, la question du fluor et de la fluoration',
'Ce travail a été cohérent et nous devons reconnaître quil a donné un excellent résultat',
'Ceci ne signifie pas quelles puissent être mieux gérées au niveau communautaire',
'Cela dit, nous sommes en désaccord, comme vous savez, sur la nécessité de modifier ou non larticle 90',
'Cela démontre, de plus, quelle na pas pris la peine de lire les conclusions du sommet extraordinaire sur lemploi',
'Cela fait également de nombreuses années que nous abordons la question d un système intégré de gestion et de contrôle dans le secteur agricole et certains pays ne peuvent toujours pas y satisfaire pleinement',
'Cela illustre à la fois l’intérêt économique que portent les banques et d’autres opérateurs à ce marché et également la réalité du surendettement, qu’il ne faut pas sous-estimer',
'Cela inclut, en particulier, les systèmes de chauffage et de conditionnement dair et de nombreux secteurs économiques (transports, petites installations industrielles, secteur des services et agriculture) qui ne sont pas couverts par le SCEQE mais contribuent encore de manière considérable aux émissions de gaz à effet de serre',
'Cela laisse à penser quà cette époque, les États membres ne voulaient pas voir, ou ne pouvaient pas voir, lorage qui sapprochait',
'Cela pose un problème souvent irritant, à savoir que, toutefois, des demandes dintervention, des demandes de motion de procédure, émanant notamment de la droite de cet hémicycle, échappent à lattention du Président',
'Cependant, la mise en ?uvre de la norme HACCP doit être considérée comme une mesure de sécurité complémentaire, qui ne peut pas se substituer aux contrôles officiels',
'Cependant, la question qui nous préoccupe est de savoir si cette mesure est proportionnelle',
'Certains m ont critiquée parce que j ai dit que je voulais donner davantage de pouvoir à l UE dans ce domaine',
'Certains matériaux, en effet, nécessitent sans doute beaucoup plus de travail ; certains, comme le verre et les métaux, peut-être moins',
'Certes, on peut entendre de belles phrases sur légalité, lemploi, la durabilité du mode de développement et la transparence',
'Ces derniers temps, la Chine utilise une pratique selon laquelle des enfants nés en Chine continentale sont séparés de leurs parents vivant à Hong-Kong',
'Ces dernières années nous ont démontré que la présence accidentelle de traces dOGM dans les produits traditionnels est devenue inévitable',
'Ces deux déclarations contiennent de très importants engagements à aller de l’avant',
'Ces deux mesures peuvent fournir les capacités requises pour couvrir les activités de défense globales et faire face aux nouveaux défis dans le domaine de la sécurité',
'Ces jours derniers, ceux-ci ont déclaré péremptoirement que le nouveau gouvernement palestinien na pas à reconnaître lennemi sioniste',
'Ces soupçons étaient suffisamment graves pour justifier une procédure judiciaire',
'Ces voix sont inquiétantes, et nous devons adopter rapidement une position claire',
'Ces évolutions doivent être suivies de près, car elles peuvent commencer à signaler des risques accrus de déstabilisation des prix, en particulier durant une période de reprise économique',
'Cet événement me rappelle ces deux Français, Jean-Claude Irvoas et Jean-Jacques Le Chenadec, lynchés pour des raisons similaires pendant les émeutes qui ont frappé les banlieues françaises l’année dernière',
'Cet événement sera la confirmation de notre souhait de construire une Europe inclusive',
'Cette attitude est inadmissible et enfreint le droit fondamental à la liberté d’expression',
'Cette convention des Nations unies devrait permettre dentraîner un changement à tous les niveaux de gouvernement - local, national et international -, en forçant les responsables politiques à reconnaître les droits des personnes handicapées dans le contexte des droits de lhomme, dune manière tout à fait nouvelle',
'Cette déclaration, cette position officielle de la haute-représentante, a également été transmise aux autorités du Belarus par la voie diplomatique',
'Cette impression négative, chers collègues, provient surtout du fait quaucun accord institutionnel na vu le jour',
'Cette opinion est partagée par le Parlement et par le Conseil dans les débats relatifs à la proposition de modification du règlement afin de prolonger le mandat de lENISA',
'Cette politique est désastreuse pour les exploitations familiales, qui constituent lépine dorsale de lagriculture européenne',
'Cette réforme doit être reportée jusquà ce quil soit convenu dun accord sur lagriculture lors des discussions sur le commerce mondial',
'Cette vigilance est absolument fondamentale pour le secteur culturel dans son ensemble: la politique culturelle a besoin dune place particulière et dun traitement particulier qui ne peut être ramené à de purs mécanismes économiques',
'Ceux qui travaillent ce sujet depuis longtemps dans le cadre de la commission sur les droits de la femme, ainsi que les organisations non gouvernementales ont depuis longtemps connaissance de ces images horribles',
]

it_test_ins = [
"""A3, 12 e 13 darebbero luogo a omissioni o incongruenze nel testo.""",
"""AA livello europeo le specifiche per i pneumatici destinati agli autoveicoli per il trasporto delle persone sono disciplinati dalla direttiva 92/23/CEE del 31 marzo 1992.""",
"""AA loro volta, più di 200 milioni di lavoratori nei paesi emergenti e in via di sviluppo corrono il rischio di essere spinti in una situazione di povertà estrema.""",
"""AA mio avviso dovremmo imparare dalla crisi e prendere una decisione, ma dubito che la nuova tassa sia quella giusta.""",
"""AA mio avviso il problema che si pone non è più tanto "perché" , quanto piuttosto, giustamente, "come" .""",
"""AA mio avviso le cose da fare sono ancora molte, anche in vista di Kyoto.""",
"""AA mio parere, il Vertice offre anche una buona occasione per compiere progressi in materia di agevolazione del rilascio dei visti e di regolamentazione del rientro degli immigrati, e consentirà di compiere ulteriori progressi nei prossimi anni per quanto concerne l’accordo di partenariato e cooperazione, necessario per porre il partenariato su basi solide, formulare la strategia per i quattro spazi comuni e ottenere dei risultati in particolare nel campo della sicurezza energetica, poiché anche la Russia deve rendersi conto che il partenariato è possibile solo se è disposta a riconoscere la libertà di tutte le nazioni nelle sue immediate vicinanze e oltre, ma anche il fatto che non bisogna permettere che diventino delle vittime in virtù di altre motivazioni.""",
"""AA mio parere, lasciare le cose come sono non è un'alternativa.""",
"""AA nome del mio gruppo, esprimo pieno sostegno a quanto affermato nei paragrafi 54 e 55 della proposta di risoluzione, con i quali si chiede che siano vietate la clonazione umana, senza riguardo per la tecnica utilizzata, e qualsiasi attività tesa a modificare la linea germinale.""",
"""AA nostro avviso, un simile provvedimento sarebbe addirittura contrario al Trattato.""",
"""AA proposito di aeroporti, le regole devono avere anche una certa flessibilità, perché è chiaro che un aeroporto come quello della Malpensa, vicino al quale io vivo, che conta settanta movimenti all'ora è ben diverso da certi aeroporti che hanno quattro o cinque movimenti al giorno.""",
"""AA quanto ho capito, eravamo d’accordo sul fatto che, se volevamo che si potessero effettuare le ristrutturazioni, dovevamo fare in modo che i dipendenti fossero coinvolti nel processo.""",
"""AA quanto mi risulta, il presidente della Federal Reserve si presenta ogni quindici giorni dinanzi al Congresso americano.""",
"""AA questo proposito credo che la liberalizzazione abbia avuto successo.""",
"""AA questo proposito dobbiamo essere disposti a rafforzare il nostro appoggio, mentre gli Stati membri dovranno modificare la propria legislazione per poter cooperare con il Tribunale.""",
"""AA questo proposito, esorto anche il Consiglio a compiere tutti gli sforzi richiesti per concludere l'accordo prima del Consiglio TELCO di giugno, in modo da poter prendere una decisione.""",
"""AA scadenza, gli aiuti debbono diminuire.""",
"""AA seguito delle elezioni, vi sono state proteste nelle strade.""",
"""AA sua volta, il Consiglio ne discuterà alla fine dello stesso mese, il 27 e 28 ottobre.""",
"""AA tal fine, i nuovi investimenti, fino alla pubblicazione delle STI, dovranno soddisfare un referenziale tecnico autorizzato.""",
"""AA tale scopo verrà istituito un pannello di controllo, o scoreboard, da rendere accessibile a tutti.""",
"""AA tutt'oggi i dati vengono trasmessi, come se non ci fosse niente di sbagliato, attraverso il sistema SWIFT.""",
"""AAbbiamo a disposizione questo strumento dotato di un potenziale enorme: perché allora, a maggior ragione visto che i bilanci pubblici corrispondono ancora al 16 per cento dell'economia europea, non utilizziamo i bilanci degli appalti pubblici per promuovere l'innovazione, per acquistare nuove tecnologie e per incentivare le PMI ad adottarle?""",
"""AAbbiamo anche piccole e medie imprese che conducono attività commerciali in tutto il mondo e anch'esse se la cavano egregiamente.""",
"""AAbbiamo anche visto quanto sia importante per noi difendere con vigore e decisione tali interessi.""",
"""AAbbiamo definito un programma dell’Unione europea teso a proteggere le infrastrutture critiche da attacchi devastanti.""",
"""AAbbiamo fatto grandi passi avanti che ci permetteranno, con l' unità d' intervento rapido operativa a partire dal 2003, di realizzare i cosiddetti compiti di Petersberg in modo autonomo, almeno sul nostro continente, o in ogni caso con il relativo mandato dell' ONU.""",
"""AAbbiamo pertanto stabilito la necessità di una politica congiunta in questo settore, nonché di una maggiore cooperazione interistituzionale, di un migliore coordinamento in materia di pianificazione, di una ricognizione delle possibilità di consolidare gli spazi ufficio in alcuni settori, e di fare un migliore uso degli appalti pubblici.""",
"""AAbbiamo poi sviluppato il sistema d'informazione del mercato interno, a cui gli Stati membri stanno facendo intensamente ricorso, e abbiamo inoltre pubblicato un codice di condotta sulle pratiche amministrative nel giugno di quest'anno.""",
"""AAbbiamo ritenuto che fosse importante compiere progressi significativi già alla nostra portata, invece di rinviare l’intero a una data futura e indefinita.""",
"""AAbbiamo sostenuto con coerenza che tale commercio è legittimo.""",
"""AAbbiamo una situazione che dimostra come vi siano anche ampie sacche di povertà e indigenza all'interno dell'Unione europea.""",
"""AAbbiamo visto quanto sia costato all'Europa un allargamento senza approfondimento. Non dobbiamo ripetere gli stessi errori.""",
"""AAccolgo con particolare favore l'accento posto sul miglioramento della normativa in tutta l'Unione, nonché l'importanza attribuita alla certezza giuridica per i servizi di interesse generale.""",
"""AAdesso occorre un ulteriore successo nella prossima conferenza intergovernativa e nella prossima modifica del Trattato e questo è certamente importantissimo.""",
"""AAdesso, finalmente, approviamo una legislazione contro le discriminazioni a livello di Unione europea.""",
"""AAggiungerei anche che nell'attuale contesto della prima fase di riflessione sul post-Nizza, il contatto con i rappresentanti dei parlamenti nazionali è ancora più necessario, ancora più prezioso di quanto non sia in periodi normali."""
]

lv_test_ins = [
""". - Nākamais darba kārtības jautājums ir Komisijas paziņojums par ietekmes novērtējumu 2008. gada jūlija beigās Dohas sarunās panāktajiem kompromisiem attiecībā uz piekļuvi ar lauksaimniecību nesaistītu ražojumu tirgum un pakalpojumiem.""",
""". - Nākamais punkts ir Padomes un Komisijas ziņojums par Eiropas Savienības stratēģiju attiecībā uz Baltkrieviju.""",
"""1. Eiropas un Vidusjūras reģiona valstu nolīgums starp EK un Maroku (Bulgārijas un Rumānijas pievienošanās) (""",
"""16. aprīlī Krievija legalizēja divpusējās attiecības un oficiālos Abhāzijas un Dienvidosetijas dokumentus.""",
"""1998. gadā 138 valstis vienojās izveidot Starptautisko Krimināltiesu un pieņēma Romas statūtus, uz kuru pamata šī tiesa darbojas jau 7 gadus, kopš 2003. gada.""",
"""2003. gadā 80 % no romu tautības iedzīvotājiem Slovākijā nebija oficiālas darba vietas, 80 % no viņiem Rumānijā un Bulgārijā ienākumi bija zemāki par valsts nabadzības slieksni, un es varētu turpināt uzskaitīt ... (Priekšsēdētāja pārtrauca runātāju) Es varētu turpināt uzskaitīt šādus gadījumus.""",
"""2006. gadā Komisija ierosināja izmantot Kopienas finansējumu no Civilās aizsardzības finanšu instrumenta, lai sniegtu papildus tādas civilās aizsardzības iekārtas kā aviācijas ugunsdzēsības vienības liela mēroga ugunsgrēkiem.""",
"""3. Divriteņu vai trīsriteņu mehānisko transportlīdzekļu ar tiesību aktiem noteiktais marķējums (kodificēta versija) (""",
""": nozares izmeklēšana banku mazumtirdzniecības pakalpojumu jomā - Zaļā grāmata par finanšu pakalpojumu mazumtirdzniecību vienotajā tirgū (debates)""",
"""ACTA apiet visas esošās starptautiskās iestādes, piemēram, Pasaules Tirdzniecības organizāciju (PTO).""",
"""ALDE grupas vārdā. - (FI) Priekšsēdētāja kungs, ES cukura politika atrodas dīvainā situācijā.""",
"""ALDE grupas vārdā. - (IT) Priekšsēdētāja kungs, dāmas un kungi! Es vēlētos pateikties Jørgensen kungam par šo ziņojumu.""",
"""Abām pusēm ir jāveicina izpratne, ka tīrām, efektīvām tehnoloģijām un "zaļām darbavietām” var būt liela nozīme ekonomikas atveseļošanā.""",
"""Aicinām Eiropas Komisiju nepadarīt vājākus esošos pasākumus savstarpējas atbilstības nodrošināšanai - tas ir pasākumus saistībā ar vides un dzīvnieku labklājību un to saderību - izmantojot tā saukto vienkāršošanu.""",
"""Aizliegums izrādījās neefektīvs un tas nepanāca no roņiem iegūto produktu tirdzniecības izbeigšanu Savienībā, kurā joprojām ir viens no lielākajiem šādiem tirgiem.""",
"""Akciju cenu kritums visā pasaulē 15.-17. septembrī radīja ieguldītājiem aptuveni 3,6 triljonu ASV dolāru lielus zaudējumus.""",
"""Alternatīva ir tāda, ka advokāti turpinās veidot politiku mūsu vietā.""",
"""Apgāzušās laivas ar nelaimīgiem patvēruma meklētājiem starp Eiropas krastiem pēdējos gados ir regulāra parādība.""",
"""Apstiprinās arī tas, ka 2007. gads ir izšķirošs attiecībā uz sagatavošanos turpmākajai darbībai.""",
"""Apsveicu, Pagano kundze.""",
"""Apvienotajā Karalistē aplēstais upuru skaits ir aptuveni 5 000 cilvēku, no kuriem 330 ir bērni.""",
"""Ar palielinātu finansējumu - gandrīz 950 miljonu eiro uz pieciem gadiem - Eiropas Savienība tagad ir spējīga apmierināt augošo pieprasījumu pēc "Erasmus Mundus” programmas.""",
"""Ar to es domāju konkurenci ar Amerikas Savienotajām Valstīm, Brazīliju un, iespējams, ļoti drīz Ķīnu.""",
"""Arī Irāna ir liela terorisma piegādātāja piemēram, Irākai, tā atbalsta Hezbollah un Hamas.""",
"""Arī starptautiskā mērogā ir pienācis īstais laiks Eiropai uzņemties saistības un veidot ciešāku saikni ar partneriem, kam ir līdzīgs pasaules redzējums.""",
"""Arī to alga būs ievērojami zemāka.""",
"""Atbildot uz Jūsu jautājumu, pamatā minētā lieta ir divpusēja.""",
"""Atbildīgās personas tiks sauktas pie atbildības saskaņā ar Polijas demokrātiskajām procedūrām.""",
"""Atbilstīgi Eiropas Savienības nolīgumi par atpakaļuzņemšanu un kopēja Eiropas Savienības imigrantu pamattiesību aizsardzība ir nepieciešama.""",
"""Atkritumi šajos rajonos bieži tiek izmesti uz ielām vai pagalmos.""",
"""Attiecībā uz Eiropas tīklu pieejamību es saskatu, ka labs risinājums ir atklātas izsoles.""",
"""Attiecībā uz Grieķijas jautājumu, par ko tika debatēts un kas tika pieminēts visvairāk, Padomes prezidentūrai ir ļoti skaidrs viedoklis.""",
"""Attiecībā uz jautājumiem, kas saistīti ar pārtikas piegādes ķēdi, it īpaši tiesībām apspriest pievienotās vērtības labāku sadali, jāsaka, ka Parlaments ir sācis darbu, Komisija ir pieņēmusi paziņojumu, un Padomē ir notikušas debates.""",
"""Attiecībā uz kopīgo vīzu pieteikumu centru Kišiņevā sadarbība starp dalībvalstīm ir jautājums, par kuru tām jālemj pašām.""",
"""Attiecībā uz tik daudziem radikāliem un progresīviem jautājumiem mēs būtu varējuši paveikt daudz vairāk.""",
"""Attiecībā uz to atļaujiet man vēlreiz atgādināt, ka viens no biodegvielu politikas mērķiem ir pārvadājumu radītās siltumnīcefekta gāzu emisijas samazināšana.""",
"""Balsojumu mutiskie skaidrojumi""",
"""Balsojumu skaidrojumi""",
"""Balsošana notiks debašu beigās.""",
"""Baznīcas skolas nevarēs izvēlēties skolotājus atbilstoši viņu reliģijai.""",
"""Bet tas nav tik svarīgi, Barroso kungs, kā pārliecināt Eiropas iedzīvotājus nākamajos piecos gados.""",
"""Bet tāpat pēdējo deviņu gadu laikā mums ir bijis izmisīgi jācīnās pret tā saucamajām krīzēm, piemēram, J. Santer Komisijas atkāpšanos un Konstitucionālā līguma noraidīšanu.""",
"""Biocīdo produktu laišana tirgū (Komisijai piešķirtās ieviešanas pilnvaras) (balsojums)""",
"""Biodegvielas risku radītā eiforija apdraud pārtikas nodrošinājumu Eiropā un pasaulē.""",
"""Budžeta komitejas vārdā sagatavotais J. Haug ziņojums par Eiropas Savienības 2009. finanšu gada budžeta grozījuma Nr. 10/2009 projektu, III iedaļa - Komisija (16327/2009 - C7-0288/2009 -;""",
"""Bēgļu problēma ir Eiropas problēma, un tās risināšanu nevar atstāt atsevišķu valstu ziņā, jo īpaši ņemot vērā to ģeogrāfiskās un ekonomiskās atšķirības."""
]
